namespace Intel.MsoAuto.C3.MailService.Notification.Core {
    public class Constants {
        public const string DEV_CONFIG = "DEV";
        public const string INT_CONFIG = "INT";
        public const string PROD_CONFIG = "PROD";
        public const string DEV = "dev";
        public const string INT = "int";
        public const string PROD = "prod";
        public const int SQL_EXEC_TIMEOUT = 180;
        public const int WORK_WEEK_LOOK_AHEAD = 13;
        public const int WEEKS_OF_A_YEAR = 52;
        public const char COMMA_DELIMITER = ',';
        public const string BOTTLENECKS = "bottlenecks";
        public const string WAITING_YA_ID = "64c2ae2aadce775a1a39caef";
        public const string SYSTEM = "system";
        public const string WORK_WEEK = "WW";
        public const string APP_SETTINGS_JSON = "appsettings.json";
        public const string CONFIGURATIONS = "Configurations";
        public const string APP_SETTINGS = "AppSettings";
        public const string ENVIRONMENT = "environment";
        public const string MONGO_DB = "MongoDb";
        public const string CONNECTION_STRING_DEV = "ConnectionStringDev";
        public const string DATABASE_NAME_DEV = "DatabaseNameDev";
        public const string CONNECTION_STRING_INT = "ConnectionStringInt";
        public const string DATABASE_NAME_INT = "DatabaseNameInt";
        public const string CONNECTION_STRING_PROD = "ConnectionStringProd";
        public const string DATABASE_NAME_PROD = "DatabaseNameProd";
        public const string ENVIRONMENT_KEY = "encryptionKey";
        public const string EMAIL = "Email";
        public const string AR_STATUS = "ArStatus";
        public const string PROGRESSION_STATUS = "ProgressionStatus";
        public const string NOTIFICATION_TEMPLATE_NAME = "NotificationTemplateName";
        public const string HAS_SENT = "HasSent";
        public const string LINK_WEBSITE_URL = "LinkWebsiteUrl";
        public const string EMAIL_FROM = "EmailFrom";
        public const string EMAIL_REDIRECT_TO = "EmailRedirectTo";
        public const string SMTP_SERVER = "SmtpServer";
        public const string PROJECT_ID = "ProjectId";
        public const string WORKFLOW_STATUS_COLLECTION_NAME = "workflowStatuses";
        public const string ACTIVE_STATUS = "active";
        public const string C3_COMMON_CONNECTION_STRING = "C3CommonConnectionString";
        public const string STATE_ID = "StateId";
        public const string APP_ID = "AppId";
        public const string SAFE_NAME = "SafeName";
        public const string CERTIFICATE_THUMBPRINT = "CertificateThumbprint";
        public const string AMQ_NAME = "AmqUserName";
        public const string AMQ_HOST_1 = "Host1";
        public const string AMQ_HOST_2 = "Host2";
        public const string AMQ_PORT = "Port";
        public const string AMQ_USER_NAME = "AmqUserName";
        public const string AMQ_TOPIC_NAME = "QueueTopicName";
        public const string AMQ_CONNECTION_STRING_FORMAT = @"failover:(ssl://{0}:{2},ssl://{1}:{2})";
        public const string XML_TRIM_1 = "<?xml version=\"1.0\" encoding=\"utf-16\"?>";
        public const string XML_TRIM_2 = "xmlns=\"\"";
        public const string ERROR_NOTIFY_TO = "ErrorNotifyTo";
        public const string EMAIL_TYPE_EXCLUSIVE = "EmailTypeExclusive";
        public const string TEMPLATE = "Template";
        public const string FAILURE_NOTIFICATION = "FailureNotification";
        public const string IS_REQUIRED = "is required";
        //----- stored procedures ------------------------------
        public const string GET_EMAIL_TEMPLATE_BY_NAME = "[note].[GetEmailTemplateByName]";
        //public const string SAVE_NOTIFICATION_EMAILS = "[note].[SaveNotificationEmails]";
        public const string SAVE_AR_ASSIGNED_NOTIFICATION_EMAILS = "[note].[SaveArAssignedNotificationEmails]";
        public const string SAVE_PROGRESSION_NOTIFICATION_EMAILS = "[note].[SaveProgressionNotificationEmails]";
        public const string GET_AR_ASSIGNED_NOTIFICATION_EMAILS = "[note].[GetArAssignedNotificationEmails]";
        public const string GET_PROGRESSION_NOTIFICATION_EMAILS = "[note].[GetProgressionNotificationEmails]";
        public const string LOOKUP_AR_ASSIGNED_TRACKED_NOTIFICATION = "[note].[LookupTrackedArAssignedNotification]";
        public const string LOOKUP_TRACKED_PROGRESSION_NOTIFICATION = "[note].[LookupTrackedProgressionNotification]";
        public const string GET_TRACKED_NOTIFICATION_BY_TYPE = "[note].[GetTrackedNotificationByType]";
        public const string LOOKUP_TRACKED_BOTTLENECK_NOTIFICATION = "[note].[LookupTrackedBottleneckNotification]";
        public const string SAVE_BOTTLENECK_NOTIFICATION_EMAILS = "[note].[SaveBottleneckNotificationEmails]";
        public const string GET_BOTTLENECK_NOTIFICATION_EMAILS = "[note].[GetBottleneckNotificationEmails]";
        //---- Default configuration values --------------------------
        public const string DEFAULT_SMTPSERVER = "ch-out.intel.com";
        public const string DEFAULT_REDIRECT_TO = "pitt_developers@intel.com";
        public const string DEFAULT_EMAIL_FROM = "sys_msoac3_preprod@intel.com";
        public const string DEFAULT_ERROR_NOTIFY_TO = "pitt_developers@intel.com";
        public const string DEFAULT_LINK_WEB_URL = "https://pitt-DevConfig.intel.com";
        public const string DEFAULT_NOTIFICATION_TOPIC_NAME = "NotificationQueue";
        public const string DEFAULT_AMQ_USER_NAME_DEV = "NotificationQueue_so";
        public const string DEFAULT_AMQ_USER_NAME_INT = "PITTNotificationQueue_rw";
        public const string DEFAULT_AMQ_USER_NAME_PROD = "PITTNotificationQueue_rw";
        public const string DEFAULT_APP_ID = "36739-PR-CERT";
        public const string DEFAULT_SAFE_NAME = "AAM-PR-PITT-36739";        
        public const string DEFAULT_C3COMMON_CONNECTION_STRING_DEV = "Data Source=sql2613-fm1s-in.amr.corp.intel.com,3181;Initial Catalog=C3Common;Integrated Security=true;";
        public const string DEFAULT_HOST_1_DEV = "10.64.5.106";
        public const string DEFAULT_HOST_2_DEV = "10.64.5.107";
        public const string DEFAULT_PORT_DEV = "8517";
        public const string DEFAULT_CERTIFICATE_THUMBPRINT_DEV = "50a75e54b18d2d62e1fe0dbe4b12aa434542bfb5";
        public const string DEFAULT_C3COMMON_CONNECTION_STRING_INT = "Data Source=sql2626-fm1s-in.amr.corp.intel.com,3181;Initial Catalog=C3Common;Integrated Security=true;";
        public const string DEFAULT_HOST_1_INT = "10.64.5.106";
        public const string DEFAULT_HOST_2_INT = "10.64.5.107";
        public const string DEFAULT_PORT_INT = "8517";
        public const string DEFAULT_CERTIFICATE_THUMBPRINT_INT = "50a75e54b18d2d62e1fe0dbe4b12aa434542bfb5";
        public const string DEFAULT_C3COMMON_CONNECTION_STRING_PROD = "Data Source=sql2626-fm1s-in.amr.corp.intel.com,3181;Initial Catalog=C3Common;Integrated Security=true;";
        public const string DEFAULT_HOST_1_PROD = "????";
        public const string DEFAULT_HOST_2_PROD = "????";
        public const string DEFAULT_PORT_PROD = "????";
        public const string DEFAULT_CERTIFICATE_THUMBPRINT_PROD = "????";
    }
}
